obstacle_range: 4.0
raytrace_range: 5.0
robot_radius: 0.2
inflation_radius: 0.75
max_obstacle_height: 1.5
min_obstacle_height: 0.0
observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: lidar_link, data_type: LaserScan, topic: base_scan, marking: true, clearing: true}
